/* eslint-disable */
/**
 * AUTO-GENERATED by protocol/codegen/generate_ts.mjs.
 * Do not edit by hand; edit the JSON Schemas under protocol/ and run:
 *   cd client && npm run gen:protocol
 */

/**
 * Free-form outbound payloads discriminated by the envelope's 'type'. The wire shape is additive-by-default (unknown keys are allowed at every level), so this container must accept any JSON value. The $defs name the shapes the server emits today and are documentation, not constraints: the envelopes carry 'payload: true'.
 */
export type ServerPayload = {} | unknown[] | string | number | boolean | null;

/**
 * Generated TypeScript view of the WebSocket protocol contract.
 */
export interface ProtocolContract {
  ClientMessage?: ClientMessage;
  Envelope?: Envelope;
  AnimationStatePayload?: AnimationStatePayload;
  EncodeConfig?: EncodeConfig;
  HubQuery?: HubQuery;
  ModelQuery?: ModelQuery;
  PipelineGraph?: PipelineGraph;
  ServerPayload?: ServerPayload;
  TrainConfig?: TrainConfig;
  ServerMessage?: ServerMessage;
}
/**
 * Inbound (browser to server) envelope. Additive-by-default: unknown fields are ignored.
 */
export interface ClientMessage {
  protocol_version: "1.0";
  type:
    | "configure"
    | "run"
    | "stop"
    | "train"
    | "stop_train"
    | "predict"
    | "select_sample"
    | "infer"
    | "save_model"
    | "list_models"
    | "load_model"
    | "delete_model"
    | "new_model"
    | "stats"
    | "cancel_download"
    | "nir_export"
    | "nir_validate"
    | "trajectory"
    | "metrics"
    | "encoding_report"
    | "surrogates"
    | "surrogate_curve"
    | "benchmark"
    | "targets"
    | "deployment_report"
    | "deploy_run"
    | "energy_report"
    | "model_search"
    | "model_diff"
    | "hub_list"
    | "hub_search"
    | "hub_download"
    | "hub_cancel"
    | "hub_inspect"
    | "hub_import"
    | "list_pipelines"
    | "save_pipeline"
    | "load_pipeline"
    | "delete_pipeline"
    | "run_pipeline"
    | "stop_pipeline";
  config?: EncodeConfig;
  train?: TrainConfig;
  query?: ModelQuery;
  hub?: HubQuery;
  name?: string | null;
  sparse?: boolean;
  pipeline?: PipelineGraph;
  /**
   * Feeds run_pipeline's source node(s): one frame per entry, raw or already-encoded per `encoded`.
   */
  pipeline_input?: {
    frames?: unknown[];
    encoded?: boolean;
  };
  [k: string]: unknown;
}
/**
 * Mirrors server/schemas/encode_config.py::EncodeConfig; defaults are documented and unknown keys are ignored.
 */
export interface EncodeConfig {
  coding?: "rate" | "latency" | "delta" | "random";
  dataset?: string;
  subset?: number;
  batch_size?: number;
  num_steps?: number;
  sample_index?: number;
  gain?: number;
  vector_value?: number;
  tau?: number;
  threshold?: number;
  clip?: boolean;
  normalize?: boolean;
  linear?: boolean;
  off_spike?: boolean;
  delta_threshold?: number;
  random_scale?: number;
  random_seed?: number | null;
  interval_ms?: number;
  /**
   * @minItems 2
   * @maxItems 2
   */
  input_size?: [number, number] | null;
  animate_hidden?: boolean;
  [k: string]: unknown;
}
/**
 * Mirrors server/schemas/train_config.py::TrainConfig; defaults are documented and unknown keys are ignored.
 */
export interface TrainConfig {
  dataset?: string;
  hidden?: number;
  beta?: number;
  lr?: number;
  epochs?: number;
  num_steps?: number;
  subset?: number;
  batch_size?: number;
  checkpoint?: string | null;
  device?: "auto" | "cpu" | "gpu";
  mode?: "educational" | "production";
  topology?: string;
  topology_params?: {
    [k: string]: unknown;
  };
  stage_neurons?: {
    [k: string]: string;
  };
  stage_params?: {
    [k: string]: {
      [k: string]: unknown;
    };
  };
  amp?: boolean;
  grad_checkpoint?: boolean;
  bptt_steps?: number | null;
  multi_gpu?: boolean;
  tracking?: "tensorboard" | "wandb" | null;
  deterministic?: boolean;
  encode?: EncodeConfig;
  [k: string]: unknown;
}
/**
 * Mirrors server/schemas/model_query.py::ModelQuery; unknown keys are ignored.
 */
export interface ModelQuery {
  dataset?: string | null;
  topology?: string | null;
  coding?: string | null;
  device?: string | null;
  min_accuracy?: number | null;
  name?: string | null;
  names?: string[];
  [k: string]: unknown;
}
/**
 * Mirrors server/schemas/hub_query.py::HubQuery; unknown keys are ignored.
 */
export interface HubQuery {
  query?: string;
  limit?: number;
  framework?: string | null;
  kind?: string | null;
  available?: boolean | null;
  topology?: string | null;
  [k: string]: unknown;
}
/**
 * Mirrors server/schemas/pipeline_graph.py::PipelineGraphConfig and spikeforge_serve.pipeline.PipelineGraph. A DAG of saved checkpoints: nodes run once each, in topological order, and a node's input is entirely determined by its incoming edge's `extract` of the upstream node's output. Semantic checks (cycles, unknown node references, fan-in) are not expressed here -- they're enforced by PipelineGraph.from_dict/validate, not this shape-only schema.
 */
export interface PipelineGraph {
  version?: number;
  name?: string;
  nodes?: {
    id: string;
    checkpoint: string;
    position?: {
      x?: number;
      y?: number;
    };
  }[];
  edges?: {
    id: string;
    source: string;
    target: string;
    extract?: "mean_logits" | "predicted_class" | "one_hot";
  }[];
}
/**
 * Shared $defs used by both the inbound and outbound envelopes. This file is the common vocabulary; each direction's envelope inlines the concrete properties so the two are independently readable.
 */
export interface Envelope {
  [k: string]: unknown;
}
/**
 * Payload of the animation_state outbound message, guarded by tests/test_client_animation_payload.py. When available is false, reason names why; source is always 'hidden'.
 *
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "animation_state".
 */
export interface AnimationStatePayload {
  available: boolean;
  reason: string;
  source?: "hidden";
  [k: string]: unknown;
}
/**
 * Outbound (server to browser) envelope. Additive-by-default: unknown fields are ignored.
 */
export interface ServerMessage {
  protocol_version: "1.0";
  type:
    | "status"
    | "image"
    | "raster"
    | "spike_frame"
    | "curve"
    | "error"
    | "config_ack"
    | "run_state"
    | "train_metrics"
    | "train_state"
    | "prediction"
    | "model_saved"
    | "model_list"
    | "model_loaded"
    | "model_cleared"
    | "inference"
    | "system_stats"
    | "download_state"
    | "nir_graph"
    | "nir_validation"
    | "trajectory"
    | "metrics"
    | "encoding_report"
    | "surrogate_list"
    | "surrogate_curve"
    | "benchmark"
    | "target_list"
    | "deployment_report"
    | "backend_run"
    | "energy_report"
    | "animation_state"
    | "hub_list"
    | "hub_search"
    | "hub_download_state"
    | "hub_inspect"
    | "hub_import"
    | "pipeline_list"
    | "pipeline_saved"
    | "pipeline_loaded"
    | "pipeline_deleted"
    | "pipeline_node_result"
    | "pipeline_run_state";
  payload?: unknown;
  source?: string | null;
  kind?: string | null;
  [k: string]: unknown;
}

/** The protocol version every outbound message must stamp. */
export const PROTOCOL_VERSION = "1.0" as const;
