#!/usr/bin/env node
/**
 * Emit client/src/protocol/generated.ts from protocol/**\/*.schema.json.
 *
 * Every schema under protocol/ is inlined into one synthetic root so the
 * JSON-Schema-to-TypeScript compiler sees a single, deduplicated document.
 * External $ref values are rewritten to local JSON pointers before compiling,
 * so no schema is ever fetched over the network even though the $id values are
 * absolute URLs.
 *
 * Run from client/ via:  npm run gen:protocol
 */

import { createRequire } from "node:module";
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const protocolDir = resolve(here, "..");
const repoRoot = resolve(protocolDir, "..");
// The dashboard repository keeps the client at its root; only the
// monorepo nests it under ``client/``.
const clientDir = existsSync(join(repoRoot, "client"))
  ? join(repoRoot, "client")
  : repoRoot;
const outFile = join(clientDir, "src", "protocol", "generated.ts");

const BANNER = [
  "/* eslint-disable */",
  "/**",
  " * AUTO-GENERATED by protocol/codegen/generate_ts.mjs.",
  " * Do not edit by hand; edit the JSON Schemas under protocol/ and run:",
  " *   cd client && npm run gen:protocol",
  " */",
  "",
].join("\n");

/** Return every *.schema.json below `dir`, skipping the codegen toolchain. */
function schemaFiles(dir) {
  const found = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      if (entry === "codegen" || entry === "node_modules") continue;
      found.push(...schemaFiles(full));
    } else if (entry.endsWith(".schema.json")) {
      found.push(full);
    }
  }
  return found.sort();
}

/** The declaration name for a schema: its title, or the file stem. */
function titleOf(schema, file) {
  if (typeof schema.title === "string" && schema.title.length > 0) {
    return schema.title;
  }
  return basename(file, ".schema.json");
}

const byName = new Map();
const loaded = [];
for (const file of schemaFiles(protocolDir)) {
  const schema = JSON.parse(readFileSync(file, "utf8"));
  byName.set(basename(file), schema);
  loaded.push(schema);
}

/** Map an external $ref to the inlined JSON pointer for its target. */
function pointerFor(ref) {
  const hash = ref.indexOf("#");
  const path = hash === -1 ? ref : ref.slice(0, hash);
  const fragment = hash === -1 ? "" : ref.slice(hash + 1);
  const target = byName.get(basename(path));
  const title = target ? titleOf(target, path) : basename(path, ".schema.json");
  const base = "#/properties/" + title;
  return fragment ? base + fragment : base;
}

/** Deep-copy a schema, dropping absolute $ids and rewriting external refs. */
function rewrite(node) {
  if (Array.isArray(node)) {
    return node.map(rewrite);
  }
  if (node !== null && typeof node === "object") {
    const out = {};
    for (const [key, value] of Object.entries(node)) {
      if (key === "$id" || key === "$schema") {
        continue;
      }
      if (key === "$ref" && typeof value === "string") {
        out[key] = value.includes(".schema.json") ? pointerFor(value) : value;
      } else {
        out[key] = rewrite(value);
      }
    }
    return out;
  }
  return node;
}

const properties = {};
for (const schema of loaded) {
  properties[titleOf(schema, "")] = rewrite(schema);
}

const root = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  title: "ProtocolContract",
  description: "Generated TypeScript view of the WebSocket protocol contract.",
  type: "object",
  properties,
};

const require = createRequire(join(clientDir, "package.json"));
const entry = pathToFileURL(require.resolve("json-schema-to-typescript")).href;
const jstt = await import(entry);
const compile = jstt.compile ?? (jstt.default && jstt.default.compile);
if (typeof compile !== "function") {
  throw new Error("json-schema-to-typescript did not export compile()");
}

const ts = await compile(root, "ProtocolContract", {
  bannerComment: BANNER,
  additionalProperties: false,
  declareExternallyReferenced: true,
  unreachableDefinitions: true,
  style: { singleQuote: false, tabWidth: 2, printWidth: 80 },
});

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, ts, "utf8");
process.stdout.write("wrote " + outFile + "\n");
